name: project-dev-resume
services:
  - name: backend
    dockerfile_path: Dockerfile.backend
    source_dir: backend
    github:
      branch: main
      deploy_on_push: true
    health_check:
      http_path: /api/health
    envs:
      - key: FLASK_ENV
        value: production
      - key: ALLOWED_ORIGINS
        value: ${_self.VITE_API_URL}
      - key: SECRET_KEY
        type: SECRET
        value: ""  # Will be set in DigitalOcean dashboard

  - name: frontend
    dockerfile_path: Dockerfile.frontend
    source_dir: .
    github:
      branch: main
      deploy_on_push: true
    routes:
      - path: /
    envs:
      - key: VITE_API_URL
        value: ${app.backend.PUBLIC_URL}

databases:
  - engine: PG
    name: portfolio-db
    num_nodes: 1
    size: basic-xs

jobs:
  - name: migrate
    kind: POST_DEPLOY
    git:
      repo_clone_url: ${_self.PUBLIC_URL}
      branch: main
    dockerfile_path: Dockerfile.backend
    envs:
      - key: DATABASE_URL
        value: ${portfolio-db.DATABASE_URL}
    command: flask db upgrade