a"""Add demo column to Project model

Revision ID: 905035d34447
Revises: c5f8d3e9a1b2
Create Date: 2025-10-11 21:23:34.397418

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '905035d34447'
down_revision = 'b50556a8e2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('demo', sa.Boolean(), nullable=False, default=False))
    # ### end Alembic commands ###


def downgrade():
    pass
