"""Add github_account field to Project model

Revision ID: c5f8d3e9a1b2
Revises: b50556a8e2da
Create Date: 2025-09-17 20:25:00.000000

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c5f8d3e9a1b2'
down_revision = 'b50556a8e2da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.add_column(sa.Column('github_account', sa.String(100), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('project', schema=None) as batch_op:
        batch_op.drop_column('github_account')
    # ### end Alembic commands ###