"""Add hybrid skill calculation fields to Skill model

Revision ID: b50556a8e2da
Revises: 
Create Date: 2025-09-12 14:07:36.145100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b50556a8e2da'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('manual_override', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('auto_calculated_level', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('project_count', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('last_calculated', sa.DateTime(), nullable=True))
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('created_at')
        batch_op.drop_column('last_calculated')
        batch_op.drop_column('project_count')
        batch_op.drop_column('auto_calculated_level')
        batch_op.drop_column('manual_override')

    # ### end Alembic commands ###
